### ISSUE TITLE
Problem adjusting finetuning examples with my data

### ISSUE THREAD

**Issue by pydn** [bfelbo/DeepMoji#36]
Hi there,

First, thank you so much for all of your work on this project. I'm really excited about the what this model can be used for.

I'm having a problem finetuning the model for my data. I'm using the finetuning_insults_chain-thaw.py example. 

My data has 5 classes and when I run it through the load_benchmark() function, it separates my data in the training, validation, and test sets that have the following shapes:
(1040, 30)
(116, 30)
(290, 30)

My labels have the following shapes:
(1040,)
(116,)
(290,)

All of my label arrays have the following unique values: [1, 2, 3, 4, 5]

I hit an error in the finetune() function where I get the following error:

`ValueError: Error when checking target: expected softmax to have shape (None, 5) but got array with shape (116, 6)`

I find this odd because the example seems to work on the benchmark data. I'm curious why my data is being reshaped in an unexpected way. If you could point me in the right direction for how to troubleshoot this I'd really appreciate it. 

Thanks!

Here is the error report:

```Loading weights for embedding
Extended vocabulary for embedding layer from 50000 to 50556 tokens.
Loading weights for bi_lstm_0
Loading weights for bi_lstm_1
Loading weights for attlayer
Ignoring weights for softmax
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_1 (InputLayer)            (None, 30)           0
__________________________________________________________________________________________________
embedding (Embedding)           (None, 30, 256)      12942336    input_1[0][0]
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 30, 256)      0           embedding[0][0]
__________________________________________________________________________________________________
embed_drop (SpatialDropout1D)   (None, 30, 256)      0           activation_1[0][0]
__________________________________________________________________________________________________
bi_lstm_0 (Bidirectional)       (None, 30, 1024)     3149824     embed_drop[0][0]
__________________________________________________________________________________________________
bi_lstm_1 (Bidirectional)       (None, 30, 1024)     6295552     bi_lstm_0[0][0]
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 30, 2304)     0           bi_lstm_1[0][0]
                                                                 bi_lstm_0[0][0]
                                                                 embed_drop[0][0]
__________________________________________________________________________________________________
attlayer (AttentionWeightedAver (None, 2304)         2304        concatenate_1[0][0]
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 2304)         0           attlayer[0][0]
__________________________________________________________________________________________________
softmax (Dense)                 (None, 5)            11525       dropout_1[0][0]
==================================================================================================
Total params: 22,401,541
Trainable params: 22,401,541
Non-trainable params: 0
__________________________________________________________________________________________________
Method:  chain-thaw
Metric:  acc
Classes: 5
Training..
WARNING:tensorflow:From .../deepmoji/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:1340: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Finetuning softmax
Traceback (most recent call last):
  File "finetune_android_chain-thaw.py", line 76, in <module>
    data['batch_size'], method='chain-thaw')
  File ".../deepmoji/finetuning.py", line 377, in finetune
    evaluate=metric, verbose=verbose)
  File "...deepmoji/finetuning.py", line 546, in chain_thaw
    batch_size=batch_size, verbose=verbose)
  File ".../deepmoji/finetuning.py", line 626, in train_by_chain_thaw
    callbacks=callbacks, verbose=(verbose >= 2))
  File ".../deepmoji/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File ".../deepmoji/lib/python2.7/site-packages/keras/engine/training.py", line 2013, in fit_generator
    val_x, val_y, val_sample_weight)
  File ".../deepmoji/lib/python2.7/site-packages/keras/engine/training.py", line 1413, in _standardize_user_data
    exception_prefix='target')
  File ".../deepmoji/lib/python2.7/site-packages/keras/engine/training.py", line 154, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected softmax to have shape (None, 5) but got array with shape (116, 6)```

**Comment by bfelbo** [comment]
Thanks for the detailed error description. You should change the label values so they start from 0 (e.g. 0 to 4). Let me know if that fixes the error :)

**Comment by pydn** [comment]
That worked. Thank you! You won't believe how many different ways I adjusted the data to make it work. It never crossed my mind to make the labels start at 0. :)
