### ISSUE TITLE
ValueError: Dimension 1 in both shapes must be equal, but are 64 and 1.

### ISSUE THREAD

**Issue by VedaNiks** [bfelbo/DeepMoji#37]
Hi,
I have finetuned the model with my data using finetune_dataset.py. When I use the finetuned model to run scripts/score_texts_emojis.py, I get the following error.

```
Traceback (most recent call last):
  File "emo_run.py", line 82, in <module>
    model = deepmoji_emojis(maxlen, PRETRAINED_PATH)
  File "C:\Users\ntelkunte\AppData\Local\Programs\Python\Python36\DeepMoji\deepmoji\model_def.py", line 58, in deepmoji_emojis
    model.load_weights(weight_path, by_name=False)
:
:
ValueError: Dimension 1 in both shapes must be equal, but are 64 and 1. Shapes are [2304,64] and [2304,1]. for 'Assign_14' (op: 'Assign') with input shapes: [2304,64], [2304,1].

```

**Comment by bfelbo** [comment]
Closing. Let me know if you're still facing this issue :)
